"""3 index refresh token

Revision ID: 30883d7a3333
Revises: 9891db4d2b35
Create Date: 2025-03-18 16:45:25.821885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30883d7a3333'
down_revision: Union[str, None] = '9891db4d2b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_auth_refresh_token'), 'user_auth', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth_refresh_token'), table_name='user_auth')
    # ### end Alembic commands ###
