"""10_add_old_users

Revision ID: 30f27c9171a4
Revises: 5c26274ed9c4
Create Date: 2025-04-28 15:38:03.106312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f27c9171a4'
down_revision: Union[str, None] = '5c26274ed9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_old', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_old')
    # ### end Alembic commands ###
