"""12-add_errores_table

Revision ID: 40e9d13fd09b
Revises: 57eda54b19fa
Create Date: 2025-05-01 10:04:57.297666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e9d13fd09b'
down_revision: Union[str, None] = '57eda54b19fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frontend_errors',
    sa.Column('error_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exception', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('error_id')
    )
    op.alter_column('users', 'is_old',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_old',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('frontend_errors')
    # ### end Alembic commands ###
