"""11_update_the_old_users

Revision ID: 57eda54b19fa
Revises: 30f27c9171a4
Create Date: 2025-04-28 15:46:42.904120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57eda54b19fa'
down_revision: Union[str, None] = '30f27c9171a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_old',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_old',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
