"""16 check missing columns

Revision ID: 648e698d9775
Revises: 56e2026ceea9
Create Date: 2025-06-03 00:05:44.767232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648e698d9775'
down_revision: Union[str, None] = '56e2026ceea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_created', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_created')
    # ### end Alembic commands ###
