"""4-refreshtokens

Revision ID: 6f4d7b602e8e
Revises: 30883d7a3333
Create Date: 2025-03-24 23:49:28.583711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f4d7b602e8e'
down_revision: Union[str, None] = '30883d7a3333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('jwt_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('hash_refresh_token', type_=sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('refresh_token_exp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_ip', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_auth_users_fky', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jwt_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_refresh_tokens_hash_refresh_token'), 'refresh_tokens', ['hash_refresh_token'], unique=False)
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.drop_index('ix_user_auth_refresh_token', table_name='user_auth')
    op.drop_column('user_auth', 'refresh_token_exp')
    op.drop_column('user_auth', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_auth', sa.Column('refresh_token_exp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_user_auth_refresh_token', 'user_auth', ['refresh_token'], unique=False)
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_index(op.f('ix_refresh_tokens_hash_refresh_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
