"""1 add countries

Revision ID: 9891db4d2b35
Revises: 16705b762b20
Create Date: 2025-03-18 00:28:55.878794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9891db4d2b35'
down_revision: Union[str, None] = '16705b762b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade():
    """Populate the countries table with initial data"""
    op.execute("""
        INSERT INTO countries (country_id, name, code, flag, calling_code) VALUES
        (1, 'Afghanistan', 'AF', 'https://www.worldometers.info/img/flags/small/tn_af-flag.gif', '+93'),
        (2, 'Albania', 'AL', 'https://www.worldometers.info/img/flags/small/tn_al-flag.gif', '+355'),
        (3, 'Algeria', 'DZ', 'https://www.worldometers.info/img/flags/small/tn_ag-flag.gif', '+213'),
        (4, 'Andorra', 'AD', 'https://www.worldometers.info/img/flags/small/tn_an-flag.gif', '+376'),
        (5, 'Angola', 'AO', 'https://www.worldometers.info/img/flags/small/tn_ao-flag.gif', '+244'),
        (6, 'Antigua and Barbuda', 'AG', 'https://www.worldometers.info/img/flags/small/tn_ac-flag.gif', '+1 (268)'),
        (7, 'Argentina', 'AR', 'https://www.worldometers.info/img/flags/small/tn_ar-flag.gif', '+54'),
        (8, 'Armenia', 'AM', 'https://www.worldometers.info/img/flags/small/tn_am-flag.gif', '+374'),
        (9, 'Australia', 'AU', 'https://www.worldometers.info/img/flags/small/tn_as-flag.gif', '+61'),
        (10, 'Austria', 'AT', 'https://www.worldometers.info/img/flags/small/tn_au-flag.gif', '+43'),
        (11, 'Azerbaijan', 'AZ', 'https://www.worldometers.info/img/flags/small/tn_aj-flag.gif', '+994'),
        (12, 'Bahamas (the)', 'BS', 'https://www.worldometers.info/img/flags/small/tn_bf-flag.gif', '+1 (242)'),
        (13, 'Bahrain', 'BH', 'https://www.worldometers.info/img/flags/small/tn_ba-flag.gif', '+973'),
        (14, 'Bangladesh', 'BD', 'https://www.worldometers.info/img/flags/small/tn_bg-flag.gif', '+880'),
        (15, 'Barbados', 'BB', 'https://www.worldometers.info/img/flags/small/tn_bb-flag.gif', '+1 (246)'),
        (16, 'Belarus', 'BY', 'https://www.worldometers.info/img/flags/small/tn_bo-flag.gif', '+375'),
        (17, 'Belgium', 'BE', 'https://www.worldometers.info/img/flags/small/tn_be-flag.gif', '+32'),
        (18, 'Belize', 'BZ', 'https://www.worldometers.info/img/flags/small/tn_bh-flag.gif', '+501'),
        (19, 'Benin', 'BJ', 'https://www.worldometers.info/img/flags/small/tn_bn-flag.gif', '+229'),
        (20, 'Bhutan', 'BT', 'https://www.worldometers.info/img/flags/small/tn_bt-flag.gif', '+975'),
        (21, 'Bolivia (Plurinational State of)', 'BO', 'https://www.worldometers.info/img/flags/small/tn_bl-flag.gif', '+591'),
        (22, 'Bosnia and Herzegovina', 'BA', 'https://www.worldometers.info/img/flags/small/tn_bk-flag.gif', '+387'),
        (23, 'Botswana', 'BW', 'https://www.worldometers.info/img/flags/small/tn_bc-flag.gif', '+267'),
        (24, 'Brazil', 'BR', 'https://www.worldometers.info/img/flags/small/tn_br-flag.gif', '+55'),
        (25, 'Brunei Darussalam', 'BN', 'https://www.worldometers.info/img/flags/small/tn_bx-flag.gif', '+673'),
        (26, 'Bulgaria', 'BG', 'https://www.worldometers.info/img/flags/small/tn_bu-flag.gif', '+359'),
        (27, 'Burkina Faso', 'BF', 'https://www.worldometers.info/img/flags/small/tn_uv-flag.gif', '+226'),
        (28, 'Burundi', 'BI', 'https://www.worldometers.info/img/flags/small/tn_by-flag.gif', '+257'),
        (29, 'Cabo Verde', 'CV', 'https://www.worldometers.info/img/flags/small/tn_cv-flag.gif', '+238'),
        (30, 'Cambodia', 'KH', 'https://www.worldometers.info/img/flags/small/tn_cb-flag.gif', '+855'),
        (31, 'Cameroon', 'CM', 'https://www.worldometers.info/img/flags/small/tn_cm-flag.gif', '+237'),
        (32, 'Canada', 'CA', 'https://www.worldometers.info/img/flags/small/tn_ca-flag.gif', '+1'),
        (33, 'Central African Republic (the)', 'CF', 'https://www.worldometers.info/img/flags/small/tn_ct-flag.gif', '+236'),
        (34, 'Chad', 'TD', 'https://www.worldometers.info/img/flags/small/tn_cd-flag.gif', '+235'),
        (35, 'Chile', 'CL', 'https://www.worldometers.info/img/flags/small/tn_ci-flag.gif', '+56'),
        (36, 'China', 'CN', 'https://www.worldometers.info/img/flags/small/tn_ch-flag.gif', '+86'),
        (37, 'Colombia', 'CO', 'https://www.worldometers.info/img/flags/small/tn_co-flag.gif', '+57'),
        (38, 'Comoros (the)', 'KM', 'https://www.worldometers.info/img/flags/small/tn_cn-flag.gif', '+269'),
        (39, 'Congo (the Democratic Republic of the)', 'CD', 'https://www.worldometers.info/img/flags/small/tn_congo-flag.gif', '+243'),
        (40, 'Congo (the)', 'CG', 'https://www.worldometers.info/img/flags/small/tn_cg-flag.gif', '+242'),
        (41, 'Costa Rica', 'CR', 'https://www.worldometers.info/img/flags/small/tn_cs-flag.gif', '+506'),
        (42, 'Côte d''Ivoire', 'CI', 'https://www.worldometers.info/img/flags/small/tn_iv-flag.gif', '+225'),
        (43, 'Croatia', 'HR', 'https://www.worldometers.info/img/flags/small/tn_hr-flag.gif', '+385'),
        (44, 'Cuba', 'CU', 'https://www.worldometers.info/img/flags/small/tn_cu-flag.gif', '+53'),
        (45, 'Cyprus', 'CY', 'https://www.worldometers.info/img/flags/small/tn_cy-flag.gif', '+357'),
        (46, 'Czechia', 'CZ', 'https://www.worldometers.info/img/flags/small/tn_ez-flag.gif', '+420'),
        (47, 'Denmark', 'DK', 'https://www.worldometers.info/img/flags/small/tn_da-flag.gif', '+45'),
        (48, 'Djibouti', 'DJ', 'https://www.worldometers.info/img/flags/small/tn_dj-flag.gif', '+253'),
        (49, 'Dominica', 'DM', 'https://www.worldometers.info/img/flags/small/tn_do-flag.gif', '+1 (767)'),
        (50, 'Dominican Republic (the)', 'DO', 'https://www.worldometers.info/img/flags/small/tn_dr-flag.gif', '+1 (809, 829, 849)'),
        (51, 'Ecuador', 'EC', 'https://www.worldometers.info/img/flags/small/tn_ec-flag.gif', '+593'),
        (52, 'Egypt', 'EG', 'https://www.worldometers.info/img/flags/small/tn_eg-flag.gif', '+20'),
        (53, 'El Salvador', 'SV', 'https://www.worldometers.info/img/flags/small/tn_es-flag.gif', '+503'),
        (54, 'Equatorial Guinea', 'GQ', 'https://www.worldometers.info/img/flags/small/tn_ek-flag.gif', '+240'),
        (55, 'Eritrea', 'ER', 'https://www.worldometers.info/img/flags/small/tn_er-flag.gif', '+291'),
        (56, 'Estonia', 'EE', 'https://www.worldometers.info/img/flags/small/tn_en-flag.gif', '+372'),
        (57, 'Eswatini', 'SZ', 'https://www.worldometers.info/img/flags/small/tn_wz-flag.gif', '+268'),
        (58, 'Ethiopia', 'ET', 'https://www.worldometers.info/img/flags/small/tn_et-flag.gif', '+251'),
        (59, 'Fiji', 'FJ', 'https://www.worldometers.info/img/flags/small/tn_fj-flag.gif', '+679'),
        (60, 'Finland', 'FI', 'https://www.worldometers.info/img/flags/small/tn_fi-flag.gif', '+358'),
        (61, 'France', 'FR', 'https://www.worldometers.info/img/flags/small/tn_fr-flag.gif', '+33'),
        (62, 'Gabon', 'GA', 'https://www.worldometers.info/img/flags/small/tn_gb-flag.gif', '+241'),
        (63, 'Gambia (the)', 'GM', 'https://www.worldometers.info/img/flags/small/tn_ga-flag.gif', '+220'),
        (64, 'Georgia', 'GE', 'https://www.worldometers.info/img/flags/small/tn_gg-flag.gif', '+995'),
        (65, 'Germany', 'DE', 'https://www.worldometers.info/img/flags/small/tn_gm-flag.gif', '+49'),
        (66, 'Ghana', 'GH', 'https://www.worldometers.info/img/flags/small/tn_gh-flag.gif', '+233'),
        (67, 'Greece', 'GR', 'https://www.worldometers.info/img/flags/small/tn_gr-flag.gif', '+30'),
        (68, 'Grenada', 'GD', 'https://www.worldometers.info/img/flags/small/tn_gj-flag.gif', '+1 (473)'),
        (69, 'Guatemala', 'GT', 'https://www.worldometers.info/img/flags/small/tn_gt-flag.gif', '+502'),
        (70, 'Guinea', 'GN', 'https://www.worldometers.info/img/flags/small/tn_gv-flag.gif', '+224'),
        (71, 'Guinea-Bissau', 'GW', 'https://www.worldometers.info/img/flags/small/tn_pu-flag.gif', '+245'),
        (72, 'Guyana', 'GY', 'https://www.worldometers.info/img/flags/small/tn_gy-flag.gif', '+592'),
        (73, 'Haiti', 'HT', 'https://www.worldometers.info/img/flags/small/tn_ha-flag.gif', '+509'),
        (74, 'Holy See (the)', 'VA', 'https://www.worldometers.info/img/flags/small/tn_vt-flag.gif', '+379'),
        (75, 'Honduras', 'HN', 'https://www.worldometers.info/img/flags/small/tn_ho-flag.gif', '+504'),
        (76, 'Hungary', 'HU', 'https://www.worldometers.info/img/flags/small/tn_hu-flag.gif', '+36'),
        (77, 'Iceland', 'IS', 'https://www.worldometers.info/img/flags/small/tn_ic-flag.gif', '+354'),
        (78, 'India', 'IN', 'https://www.worldometers.info/img/flags/small/tn_in-flag.gif', '+91'),
        (79, 'Indonesia', 'ID', 'https://www.worldometers.info/img/flags/small/tn_id-flag.gif', '+62'),
        (80, 'Iran (Islamic Republic of)', 'IR', 'https://www.worldometers.info/img/flags/small/tn_ir-flag.gif', '+98'),
        (81, 'Iraq', 'IQ', 'https://www.worldometers.info/img/flags/small/tn_iz-flag.gif', '+964'),
        (82, 'Ireland', 'IE', 'https://www.worldometers.info/img/flags/small/tn_ei-flag.gif', '+353'),
        (83, 'Israel', 'IL', 'https://www.worldometers.info/img/flags/small/tn_is-flag.gif', '+972'),
        (84, 'Italy', 'IT', 'https://www.worldometers.info/img/flags/small/tn_it-flag.gif', '+39'),
        (85, 'Jamaica', 'JM', 'https://www.worldometers.info/img/flags/small/tn_jm-flag.gif', '+1 (876)'),
        (86, 'Japan', 'JP', 'https://www.worldometers.info/img/flags/small/tn_ja-flag.gif', '+81'),
        (87, 'Jordan', 'JO', 'https://www.worldometers.info/img/flags/small/tn_jo-flag.gif', '+962'),
        (88, 'Kazakhstan', 'KZ', 'https://www.worldometers.info/img/flags/small/tn_kz-flag.gif', '+7'),
        (89, 'Kenya', 'KE', 'https://www.worldometers.info/img/flags/small/tn_ke-flag.gif', '+254'),
        (90, 'Kiribati', 'KI', 'https://www.worldometers.info/img/flags/small/tn_kr-flag.gif', '+686'),
        (91, 'Korea (the Democratic People''s Republic of)', 'KP', 'https://www.worldometers.info/img/flags/small/tn_kn-flag.gif', '+850'),
        (92, 'Korea (the Republic of)', 'KR', 'https://www.worldometers.info/img/flags/small/tn_ks-flag.gif', '+82'),
        (93, 'Kuwait', 'KW', 'https://www.worldometers.info/img/flags/small/tn_ku-flag.gif', '+965'),
        (94, 'Kyrgyzstan', 'KG', 'https://www.worldometers.info/img/flags/small/tn_kg-flag.gif', '+996'),
        (95, 'Lao People''s Democratic Republic (the)', 'LA', 'https://www.worldometers.info/img/flags/small/tn_la-flag.gif', '+856'),
        (96, 'Latvia', 'LV', 'https://www.worldometers.info/img/flags/small/tn_lg-flag.gif', '+371'),
        (97, 'Lebanon', 'LB', 'https://www.worldometers.info/img/flags/small/tn_le-flag.gif', '+961'),
        (98, 'Lesotho', 'LS', 'https://www.worldometers.info/img/flags/small/tn_lt-flag.gif', '+266'),
        (99, 'Liberia', 'LR', 'https://www.worldometers.info/img/flags/small/tn_li-flag.gif', '+231'),
        (100, 'Libya', 'LY', 'https://www.worldometers.info/img/flags/small/tn_ly-flag.gif', '+218'),
        (101, 'Liechtenstein', 'LI', 'https://www.worldometers.info/img/flags/small/tn_ls-flag.gif', '+423'),
        (102, 'Lithuania', 'LT', 'https://www.worldometers.info/img/flags/small/tn_lh-flag.gif', '+370'),
        (103, 'Luxembourg', 'LU', 'https://www.worldometers.info/img/flags/small/tn_lu-flag.gif', '+352'),
        (104, 'Madagascar', 'MG', 'https://www.worldometers.info/img/flags/small/tn_ma-flag.gif', '+261'),
        (105, 'Malawi', 'MW', 'https://www.worldometers.info/img/flags/small/tn_mi-flag.gif', '+265'),
        (106, 'Malaysia', 'MY', 'https://www.worldometers.info/img/flags/small/tn_my-flag.gif', '+60'),
        (107, 'Maldives', 'MV', 'https://www.worldometers.info/img/flags/small/tn_mv-flag.gif', '+960'),
        (108, 'Mali', 'ML', 'https://www.worldometers.info/img/flags/small/tn_ml-flag.gif', '+223'),
        (109, 'Malta', 'MT', 'https://www.worldometers.info/img/flags/small/tn_mt-flag.gif', '+356'),
        (110, 'Marshall Islands (the)', 'MH', 'https://www.worldometers.info/img/flags/small/tn_rm-flag.gif', '+692'),
        (111, 'Mauritania', 'MR', 'https://www.worldometers.info/img/flags/small/tn_mr-flag.gif', '+222'),
        (112, 'Mauritius', 'MU', 'https://www.worldometers.info/img/flags/small/tn_mp-flag.gif', '+230'),
        (113, 'Mexico', 'MX', 'https://www.worldometers.info/img/flags/small/tn_mx-flag.gif', '+52'),
        (114, 'Micronesia (Federated States of)', 'FM', 'https://www.worldometers.info/img/flags/small/tn_fm-flag.gif', '+691'),
        (115, 'Moldova (the Republic of)', 'MD', 'https://www.worldometers.info/img/flags/small/tn_md-flag.gif', '+373'),
        (116, 'Monaco', 'MC', 'https://www.worldometers.info/img/flags/small/tn_mn-flag.gif', '+377'),
        (117, 'Mongolia', 'MN', 'https://www.worldometers.info/img/flags/small/tn_mg-flag.gif', '+976'),
        (118, 'Montenegro', 'ME', 'https://www.worldometers.info/img/flags/small/tn_mj-flag.gif', '+382'),
        (119, 'Morocco', 'MA', 'https://www.worldometers.info/img/flags/small/tn_mo-flag.gif', '+212'),
        (120, 'Mozambique', 'MZ', 'https://www.worldometers.info/img/flags/small/tn_mz-flag.gif', '+258'),
        (121, 'Myanmar', 'MM', 'https://www.worldometers.info/img/flags/small/tn_bm-flag.gif', '+95'),
        (122, 'Namibia', 'NA', 'https://www.worldometers.info/img/flags/small/tn_wa-flag.gif', '+264'),
        (123, 'Nauru', 'NR', 'https://www.worldometers.info/img/flags/small/tn_nr-flag.gif', '+674'),
        (124, 'Nepal', 'NP', 'https://www.worldometers.info/img/flags/small/tn_np-flag.gif', '+977'),
        (125, 'Netherlands (the)', 'NL', 'https://www.worldometers.info/img/flags/small/tn_nl-flag.gif', '+31'),
        (126, 'New Zealand', 'NZ', 'https://www.worldometers.info/img/flags/small/tn_nz-flag.gif', '+64'),
        (127, 'Nicaragua', 'NI', 'https://www.worldometers.info/img/flags/small/tn_nu-flag.gif', '+505'),
        (128, 'Niger (the)', 'NE', 'https://www.worldometers.info/img/flags/small/tn_ng-flag.gif', '+227'),
        (129, 'Nigeria', 'NG', 'https://www.worldometers.info/img/flags/small/tn_ni-flag.gif', '+234'),
        (130, 'Norway', 'NO', 'https://www.worldometers.info/img/flags/small/tn_no-flag.gif', '+47'),
        (131, 'Oman', 'OM', 'https://www.worldometers.info/img/flags/small/tn_mu-flag.gif', '+968'),
        (132, 'Pakistan', 'PK', 'https://www.worldometers.info/img/flags/small/tn_pk-flag.gif', '+92'),
        (133, 'Palau', 'PW', 'https://www.worldometers.info/img/flags/small/tn_ps-flag.gif', '+680'),
        (134, 'Palestine, State of', 'PS', 'https://www.worldometers.info/img/flags/small/tn_palestine-flag.gif', '+970'),
        (135, 'Panama', 'PA', 'https://www.worldometers.info/img/flags/small/tn_pm-flag.gif', '+507'),
        (136, 'Papua New Guinea', 'PG', 'https://www.worldometers.info/img/flags/small/tn_pp-flag.gif', '+675'),
        (137, 'Paraguay', 'PY', 'https://www.worldometers.info/img/flags/small/tn_pa-flag.gif', '+595'),
        (138, 'Peru', 'PE', 'https://www.worldometers.info/img/flags/small/tn_pe-flag.gif', '+51'),
        (139, 'Philippines (the)', 'PH', 'https://www.worldometers.info/img/flags/small/tn_rp-flag.gif', '+63'),
        (140, 'Poland', 'PL', 'https://www.worldometers.info/img/flags/small/tn_pl-flag.gif', '+48'),
        (141, 'Portugal', 'PT', 'https://www.worldometers.info/img/flags/small/tn_po-flag.gif', '+351'),
        (142, 'Qatar', 'QA', 'https://www.worldometers.info/img/flags/small/tn_qa-flag.gif', '+974'),
        (143, 'Republic of North Macedonia', 'MK', 'https://www.worldometers.info/img/flags/small/tn_mk-flag.gif', '+389'),
        (144, 'Romania', 'RO', 'https://www.worldometers.info/img/flags/small/tn_ro-flag.gif', '+40'),
        (145, 'Russian Federation (the)', 'RU', 'https://www.worldometers.info/img/flags/small/tn_rs-flag.gif', '+7'),
        (146, 'Rwanda', 'RW', 'https://www.worldometers.info/img/flags/small/tn_rw-flag.gif', '+250'),
        (147, 'Saint Kitts and Nevis', 'KN', 'https://www.worldometers.info/img/flags/small/tn_sc-flag.gif', '+1 (869)'),
        (148, 'Saint Lucia', 'LC', 'https://www.worldometers.info/img/flags/small/tn_st-flag.gif', '+1 (758)'),
        (149, 'Saint Vincent and the Grenadines', 'VC', 'https://www.worldometers.info/img/flags/small/tn_vc-flag.gif', '+1 (784)'),
        (150, 'Samoa', 'WS', 'https://www.worldometers.info/img/flags/small/tn_ws-flag.gif', '+685'),
        (151, 'San Marino', 'SM', 'https://www.worldometers.info/img/flags/small/tn_sm-flag.gif', '+378'),
        (152, 'Sao Tome and Principe', 'ST', 'https://www.worldometers.info/img/flags/small/tn_tp-flag.gif', '+239'),
        (153, 'Saudi Arabia', 'SA', 'https://www.worldometers.info/img/flags/small/tn_sa-flag.gif', '+966'),
        (154, 'Senegal', 'SN', 'https://www.worldometers.info/img/flags/small/tn_sg-flag.gif', '+221'),
        (155, 'Serbia', 'RS', 'https://www.worldometers.info/img/flags/small/tn_ri-flag.gif', '+381'),
        (156, 'Seychelles', 'SC', 'https://www.worldometers.info/img/flags/small/tn_se-flag.gif', '+248'),
        (157, 'Sierra Leone', 'SL', 'https://www.worldometers.info/img/flags/small/tn_sl-flag.gif', '+232'),
        (158, 'Singapore', 'SG', 'https://www.worldometers.info/img/flags/small/tn_sn-flag.gif', '+65'),
        (159, 'Slovakia', 'SK', 'https://www.worldometers.info/img/flags/small/tn_lo-flag.gif', '+421'),
        (160, 'Slovenia', 'SI', 'https://www.worldometers.info/img/flags/small/tn_si-flag.gif', '+386'),
        (161, 'Solomon Islands', 'SB', 'https://www.worldometers.info/img/flags/small/tn_bp-flag.gif', '+677'),
        (162, 'Somalia', 'SO', 'https://www.worldometers.info/img/flags/small/tn_so-flag.gif', '+252'),
        (163, 'South Africa', 'ZA', 'https://www.worldometers.info/img/flags/small/tn_sf-flag.gif', '+27'),
        (164, 'South Sudan', 'SS', 'https://www.worldometers.info/img/flags/small/tn_od-flag.gif', '+211'),
        (165, 'Spain', 'ES', 'https://www.worldometers.info/img/flags/small/tn_sp-flag.gif', '+34'),
        (166, 'Sri Lanka', 'LK', 'https://www.worldometers.info/img/flags/small/tn_ce-flag.gif', '+94'),
        (167, 'Sudan (the)', 'SD', 'https://www.worldometers.info/img/flags/small/tn_su-flag.gif', '+249'),
        (168, 'Suriname', 'SR', 'https://www.worldometers.info/img/flags/small/tn_ns-flag.gif', '+597'),
        (169, 'Sweden', 'SE', 'https://www.worldometers.info/img/flags/small/tn_sw-flag.gif', '+46'),
        (170, 'Switzerland', 'CH', 'https://www.worldometers.info/img/flags/small/tn_sz-flag.gif', '+41'),
        (171, 'Syrian Arab Republic', 'SY', 'https://www.worldometers.info/img/flags/small/tn_sy-flag.gif', '+963'),
        (172, 'Tajikistan', 'TJ', 'https://www.worldometers.info/img/flags/small/tn_ti-flag.gif', '+992'),
        (173, 'Tanzania, United Republic of', 'TZ', 'https://www.worldometers.info/img/flags/small/tn_tz-flag.gif', '+255'),
        (174, 'Thailand', 'TH', 'https://www.worldometers.info/img/flags/small/tn_th-flag.gif', '+66'),
        (175, 'Timor-Leste', 'TL', 'https://www.worldometers.info/img/flags/small/tn_tt-flag.gif', '+670'),
        (176, 'Togo', 'TG', 'https://www.worldometers.info/img/flags/small/tn_to-flag.gif', '+228'),
        (177, 'Tonga', 'TO', 'https://www.worldometers.info/img/flags/small/tn_tn-flag.gif', '+676'),
        (178, 'Trinidad and Tobago', 'TT', 'https://www.worldometers.info/img/flags/small/tn_td-flag.gif', '+1 (868)'),
        (179, 'Tunisia', 'TN', 'https://www.worldometers.info/img/flags/small/tn_ts-flag.gif', '+216'),
        (180, 'Turkey', 'TR', 'https://www.worldometers.info/img/flags/small/tn_tu-flag.gif', '+90'),
        (181, 'Turkmenistan', 'TM', 'https://www.worldometers.info/img/flags/small/tn_tx-flag.gif', '+993'),
        (182, 'Tuvalu', 'TV', 'https://www.worldometers.info/img/flags/small/tn_tv-flag.gif', '+688'),
        (183, 'Uganda', 'UG', 'https://www.worldometers.info/img/flags/small/tn_ug-flag.gif', '+256'),
        (184, 'Ukraine', 'UA', 'https://www.worldometers.info/img/flags/small/tn_up-flag.gif', '+380'),
        (185, 'United Arab Emirates (the)', 'AE', 'https://www.worldometers.info/img/flags/small/tn_ae-flag.gif', '+971'),
        (186, 'United Kingdom of Great Britain and Northern Ireland (the)', 'GB', 'https://www.worldometers.info/img/flags/small/tn_uk-flag.gif', '+44'),
        (187, 'United States of America (the)', 'US', 'https://www.worldometers.info/img/flags/small/tn_us-flag.gif', '+1'),
        (188, 'Uruguay', 'UY', 'https://www.worldometers.info/img/flags/small/tn_uy-flag.gif', '+598'),
        (189, 'Uzbekistan', 'UZ', 'https://www.worldometers.info/img/flags/small/tn_uz-flag.gif', '+998'),
        (190, 'Vanuatu', 'VU', 'https://www.worldometers.info/img/flags/small/tn_nh-flag.gif', '+678'),
        (191, 'Venezuela (Bolivarian Republic of)', 'VE', 'https://www.worldometers.info/img/flags/small/tn_ve-flag.gif', '+58'),
        (192, 'Viet Nam', 'VN', 'https://www.worldometers.info/img/flags/small/tn_vm-flag.gif', '+84'),
        (193, 'Yemen', 'YE', 'https://www.worldometers.info/img/flags/small/tn_ym-flag.gif', '+967'),
        (194, 'Zambia', 'ZM', 'https://www.worldometers.info/img/flags/small/tn_za-flag.gif', '+260'),
        (195, 'Zimbabwe', 'ZW', 'https://www.worldometers.info/img/flags/small/tn_zi-flag.gif', '+263')
    """)


def downgrade():
    """Rollback the countries table data"""
    op.execute("""
    DELETE FROM countries;
    """)
