"""8-remove_unique_from_user_id_on_RT_Table

Revision ID: b74386e59e0a
Revises: d0592facc9b4
Create Date: 2025-03-28 17:37:51.311906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74386e59e0a'
down_revision: Union[str, None] = 'd0592facc9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_user_id_key', 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('refresh_tokens_user_id_key', 'refresh_tokens', ['user_id'])
    # ### end Alembic commands ###
