"""7-add-blaklistfalge

Revision ID: d0592facc9b4
Revises: c054e39de9e4
Create Date: 2025-03-28 16:28:29.976361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0592facc9b4'
down_revision: Union[str, None] = 'c054e39de9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_blackList', sa.Boolean(), nullable=False))
    op.alter_column('refresh_tokens', 'hash_refresh_token',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'hash_refresh_token',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.drop_column('refresh_tokens', 'is_blackList')
    # ### end Alembic commands ###
