"""17_add_CONTENT_MANAGER

Revision ID: f4df321581c9
Revises: d7f8eae230dd
Create Date: 2025-06-18 11:58:42.350000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4df321581c9'
down_revision: Union[str, None] = 'd7f8eae230dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'CONTENT_MANAGER';")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'TEAM_MEMBER';")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
