"""5-array_text

Revision ID: f5f4fefff3eb
Revises: 6f4d7b602e8e
Create Date: 2025-03-25 00:10:07.126270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f4fefff3eb'
down_revision: Union[str, None] = '6f4d7b602e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'hash_refresh_token',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'hash_refresh_token',
               existing_type=sa.ARRAY(sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
